/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import IssueRefundRequest from '../model/IssueRefundRequest';
import Order from '../model/Order';
import OrderSearchPagedCollection from '../model/OrderSearchPagedCollection';
import Refund from '../model/Refund';

/**
* Order service.
* @module api/OrderApi
* @version v1.17.0
*/
export default class OrderApi {

    /**
    * Constructs a new OrderApi. 
    * @alias module:api/OrderApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getOrder operation.
     * @callback module:api/OrderApi~getOrderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Use this call to retrieve the contents of an order based on its unique identifier, orderId. This value was returned in the getOrders call&#x27;s orders.orderId field when you searched for orders by creation date, modification date, or fulfillment status. Include the optional fieldGroups query parmeter set to TAX_BREAKDOWN to return a breakdown of the taxes and fees. The returned Order object contains information you can use to create and process fulfillments, including: Information about the buyer and seller Information about the order&#x27;s line items The plans for packaging, addressing and shipping the order The status of payment, packaging, addressing, and shipping the order A summary of monetary amounts specific to the order such as pricing, payments, and shipping costs A summary of applied taxes and fees, and optionally a breakdown of each
     * @param {Object} opts Optional parameters
     * @param {module:api/OrderApi~getOrderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Order}
     */
    getOrder(orderId, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
        'fieldGroups': opts['fieldGroups']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Order;

      return this.apiClient.callApi(
        '/order/{orderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getOrders operation.
     * @callback module:api/OrderApi~getOrdersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderSearchPagedCollection} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Use this call to search for and retrieve one or more orders based on their creation date, last modification date, or fulfillment status using the filter parameter. You can alternatively specify a list of orders using the orderIds parameter. Include the optional fieldGroups query parmeter set to TAX_BREAKDOWN to return a breakdown of the taxes and fees. The returned Order objects contain information you can use to create and process fulfillments, including: Information about the buyer and seller Information about the order&#x27;s line items The plans for packaging, addressing and shipping the order The status of payment, packaging, addressing, and shipping the order A summary of monetary amounts specific to the order such as pricing, payments, and shipping costs A summary of applied taxes and fees, and optionally a breakdown of each Important: In this call, the cancelStatus.cancelRequests array is returned but is always empty. Use the getOrder call instead, which returns this array fully populated with information about any cancellation requests.
     * @param {Object} opts Optional parameters
     * @param {module:api/OrderApi~getOrdersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderSearchPagedCollection}
     */
    getOrders(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'fieldGroups': opts['fieldGroups'],
        'filter': opts['filter'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'orderIds': opts['orderIds']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OrderSearchPagedCollection;

      return this.apiClient.callApi(
        '/order', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the issueRefund operation.
     * @callback module:api/OrderApi~issueRefundCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Refund} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Issue Refund
     * This method allows a seller (opted in to eBay Managed Payments) to issue a full or partial refund to a buyer for an order. Full or partial refunds can be issued at the order level or line item level. The refunds issued through this method are processed asynchronously, so the refund will not show as &#x27;Refunded&#x27; right away. A seller will have to make a subsequent getOrder call to check the status of the refund. The status of an order refund can be found in the paymentSummary.refunds.refundStatus field of the getOrder response. Note: eBay Managed Payments is currently only available to a limited number of US sellers, but this program is scheduled to become available to more sellers throughout 2019 and beyond.
     * @param {Object} opts Optional parameters
     * @param {module:api/OrderApi~issueRefundCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Refund}
     */
    issueRefund(orderId, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        'order_id': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Refund;

      return this.apiClient.callApi(
        '/order/{order_id}/issue_refund', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
