/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FulfillmentApi);
  }
}(this, function(expect, FulfillmentApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FulfillmentApi.Error();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Error', function() {
    it('should create an instance of Error', function() {
      // uncomment below and update the code to test Error
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be.a(FulfillmentApi.Error);
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property errorId (base name: "errorId")', function() {
      // uncomment below and update the code to test the property errorId
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property inputRefIds (base name: "inputRefIds")', function() {
      // uncomment below and update the code to test the property inputRefIds
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property longMessage (base name: "longMessage")', function() {
      // uncomment below and update the code to test the property longMessage
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property outputRefIds (base name: "outputRefIds")', function() {
      // uncomment below and update the code to test the property outputRefIds
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property parameters (base name: "parameters")', function() {
      // uncomment below and update the code to test the property parameters
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

    it('should have the property subdomain (base name: "subdomain")', function() {
      // uncomment below and update the code to test the property subdomain
      //var instane = new FulfillmentApi.Error();
      //expect(instance).to.be();
    });

  });

}));
