/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AddEvidencePaymentDisputeResponse model module.
* @module model/AddEvidencePaymentDisputeResponse
* @version v1.17.0
*/
export default class AddEvidencePaymentDisputeResponse {
    /**
    * Constructs a new <code>AddEvidencePaymentDisputeResponse</code>.
    * This type is used by the response payload of the addEvidence method. Its only field is an unique identifier of an evidence set.
    * @alias module:model/AddEvidencePaymentDisputeResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AddEvidencePaymentDisputeResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddEvidencePaymentDisputeResponse} obj Optional instance to populate.
    * @return {module:model/AddEvidencePaymentDisputeResponse} The populated <code>AddEvidencePaymentDisputeResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddEvidencePaymentDisputeResponse();
                        
            
            if (data.hasOwnProperty('evidenceId')) {
                obj['evidenceId'] = ApiClient.convertToType(data['evidenceId'], 'String');
            }
        }
        return obj;
    }

    /**
    * The value returned in this field is the unique identifier of the newly-created evidence set. Upon a successful call, this value is automatically genererated. This new evidence set for the payment dispute includes the evidence file(s) that were passed in to the fileId array in the request payload. The evidenceId value will be needed if the seller wishes to add to the evidence set by using the updateEvidence method, or if they want to retrieve a specific evidence file within the evidence set by using the fetchEvidenceContent method.
    * @member {String} evidenceId
    */
    'evidenceId' = undefined;




}
