/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';

/**
* The AppliedPromotion model module.
* @module model/AppliedPromotion
* @version v1.17.0
*/
export default class AppliedPromotion {
    /**
    * Constructs a new <code>AppliedPromotion</code>.
    * This type contains information about a sales promotion that is applied to a line item.
    * @alias module:model/AppliedPromotion
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AppliedPromotion</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AppliedPromotion} obj Optional instance to populate.
    * @return {module:model/AppliedPromotion} The populated <code>AppliedPromotion</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppliedPromotion();
                        
            
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('discountAmount')) {
                obj['discountAmount'] = Amount.constructFromObject(data['discountAmount']);
            }
            if (data.hasOwnProperty('promotionId')) {
                obj['promotionId'] = ApiClient.convertToType(data['promotionId'], 'String');
            }
        }
        return obj;
    }

    /**
    * A description of the applied sales promotion.
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {module:model/Amount} discountAmount
    */
    'discountAmount' = undefined;
    /**
    * An eBay-generated unique identifier of the sales promotion. Multiple types of sales promotions are available to eBay Store owners, including order size/volume discounts, shipping discounts, special coupons, and price markdowns. Sales promotions can be managed through the Marketing tab of Seller Hub in My eBay, or by using the Trading API's SetPromotionalSale call or the Marketing API's createItemPromotion method.
    * @member {String} promotionId
    */
    'promotionId' = undefined;




}
