/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaxIdentifier from './TaxIdentifier';

/**
* The Buyer model module.
* @module model/Buyer
* @version v1.17.0
*/
export default class Buyer {
    /**
    * Constructs a new <code>Buyer</code>.
    * This type contains information about the order&#x27;s buyer.
    * @alias module:model/Buyer
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Buyer</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Buyer} obj Optional instance to populate.
    * @return {module:model/Buyer} The populated <code>Buyer</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Buyer();
                        
            
            if (data.hasOwnProperty('taxIdentifier')) {
                obj['taxIdentifier'] = TaxIdentifier.constructFromObject(data['taxIdentifier']);
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/TaxIdentifier} taxIdentifier
    */
    'taxIdentifier' = undefined;
    /**
    * The buyer's eBay user ID.
    * @member {String} username
    */
    'username' = undefined;




}
