/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CancelRequest model module.
* @module model/CancelRequest
* @version v1.17.0
*/
export default class CancelRequest {
    /**
    * Constructs a new <code>CancelRequest</code>.
    * This type contains information about a buyer request to cancel an order.
    * @alias module:model/CancelRequest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CancelRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CancelRequest} obj Optional instance to populate.
    * @return {module:model/CancelRequest} The populated <code>CancelRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancelRequest();
                        
            
            if (data.hasOwnProperty('cancelCompletedDate')) {
                obj['cancelCompletedDate'] = ApiClient.convertToType(data['cancelCompletedDate'], 'String');
            }
            if (data.hasOwnProperty('cancelInitiator')) {
                obj['cancelInitiator'] = ApiClient.convertToType(data['cancelInitiator'], 'String');
            }
            if (data.hasOwnProperty('cancelReason')) {
                obj['cancelReason'] = ApiClient.convertToType(data['cancelReason'], 'String');
            }
            if (data.hasOwnProperty('cancelRequestedDate')) {
                obj['cancelRequestedDate'] = ApiClient.convertToType(data['cancelRequestedDate'], 'String');
            }
            if (data.hasOwnProperty('cancelRequestId')) {
                obj['cancelRequestId'] = ApiClient.convertToType(data['cancelRequestId'], 'String');
            }
            if (data.hasOwnProperty('cancelRequestState')) {
                obj['cancelRequestState'] = ApiClient.convertToType(data['cancelRequestState'], 'String');
            }
        }
        return obj;
    }

    /**
    * The date and time that the order cancellation was completed, if applicable. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. This field is not returned until the cancellation request has actually been approved by the seller. Format: [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z Example: 2015-08-04T19:09:02.768Z
    * @member {String} cancelCompletedDate
    */
    'cancelCompletedDate' = undefined;
    /**
    * This string value indicates the party who made the initial cancellation request. Typically, either the 'Buyer' or 'Seller'. If a cancellation request has been made, this field should be returned.
    * @member {String} cancelInitiator
    */
    'cancelInitiator' = undefined;
    /**
    * The reason why the cancelInitiator initiated the cancellation request. Cancellation reasons for a buyer might include 'order placed by mistake' or 'order won't arrive in time'. For a seller, a typical cancellation reason is 'out of stock'. If a cancellation request has been made, this field should be returned.
    * @member {String} cancelReason
    */
    'cancelReason' = undefined;
    /**
    * The date and time that the order cancellation was requested. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. This field is returned for each cancellation request. Format: [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z Example: 2015-08-04T19:09:02.768Z
    * @member {String} cancelRequestedDate
    */
    'cancelRequestedDate' = undefined;
    /**
    * The unique identifier of the order cancellation request. This field is returned for each cancellation request.
    * @member {String} cancelRequestId
    */
    'cancelRequestId' = undefined;
    /**
    * The current stage or condition of the cancellation request. This field is returned for each cancellation request. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:CancelRequestStateEnum'>eBay API documentation</a>
    * @member {String} cancelRequestState
    */
    'cancelRequestState' = undefined;




}
