/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CancelRequest from './CancelRequest';

/**
* The CancelStatus model module.
* @module model/CancelStatus
* @version v1.17.0
*/
export default class CancelStatus {
    /**
    * Constructs a new <code>CancelStatus</code>.
    * This type contains information about any requests that have been made to cancel an order.
    * @alias module:model/CancelStatus
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CancelStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CancelStatus} obj Optional instance to populate.
    * @return {module:model/CancelStatus} The populated <code>CancelStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancelStatus();
                        
            
            if (data.hasOwnProperty('cancelledDate')) {
                obj['cancelledDate'] = ApiClient.convertToType(data['cancelledDate'], 'String');
            }
            if (data.hasOwnProperty('cancelRequests')) {
                obj['cancelRequests'] = ApiClient.convertToType(data['cancelRequests'], [CancelRequest]);
            }
            if (data.hasOwnProperty('cancelState')) {
                obj['cancelState'] = ApiClient.convertToType(data['cancelState'], 'String');
            }
        }
        return obj;
    }

    /**
    * The date and time the order was cancelled, if applicable. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. Format: [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z Example: 2015-08-04T19:09:02.768Z
    * @member {String} cancelledDate
    */
    'cancelledDate' = undefined;
    /**
    * This array contains details of one or more buyer requests to cancel the order. For the getOrders call: This array is returned but is always empty. For the getOrder call: This array is returned fully populated with information about any cancellation requests.
    * @member {Array.<module:model/CancelRequest>} cancelRequests
    */
    'cancelRequests' = undefined;
    /**
    * The state of the order with regard to cancellation. This field is always returned, and if there are no cancellation requests, a value of NONE_REQUESTED is returned. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:CancelStateEnum'>eBay API documentation</a>
    * @member {String} cancelState
    */
    'cancelState' = undefined;




}
