/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';

/**
* The DeliveryCost model module.
* @module model/DeliveryCost
* @version v1.17.0
*/
export default class DeliveryCost {
    /**
    * Constructs a new <code>DeliveryCost</code>.
    * This type contains a breakdown of all costs associated with the fulfillment of a line item.
    * @alias module:model/DeliveryCost
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DeliveryCost</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DeliveryCost} obj Optional instance to populate.
    * @return {module:model/DeliveryCost} The populated <code>DeliveryCost</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliveryCost();
                        
            
            if (data.hasOwnProperty('importCharges')) {
                obj['importCharges'] = Amount.constructFromObject(data['importCharges']);
            }
            if (data.hasOwnProperty('shippingCost')) {
                obj['shippingCost'] = Amount.constructFromObject(data['shippingCost']);
            }
            if (data.hasOwnProperty('shippingIntermediationFee')) {
                obj['shippingIntermediationFee'] = Amount.constructFromObject(data['shippingIntermediationFee']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Amount} importCharges
    */
    'importCharges' = undefined;
    /**
    * @member {module:model/Amount} shippingCost
    */
    'shippingCost' = undefined;
    /**
    * @member {module:model/Amount} shippingIntermediationFee
    */
    'shippingIntermediationFee' = undefined;




}
