/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentDisputeSummary from './PaymentDisputeSummary';

/**
* The DisputeSummaryResponse model module.
* @module model/DisputeSummaryResponse
* @version v1.17.0
*/
export default class DisputeSummaryResponse {
    /**
    * Constructs a new <code>DisputeSummaryResponse</code>.
    * This type defines the base response payload of the getPaymentDisputeSummaries method. Each payment dispute that matches the input criteria is returned under the paymentDisputeSummaries array.
    * @alias module:model/DisputeSummaryResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>DisputeSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DisputeSummaryResponse} obj Optional instance to populate.
    * @return {module:model/DisputeSummaryResponse} The populated <code>DisputeSummaryResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DisputeSummaryResponse();
                        
            
            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('paymentDisputeSummaries')) {
                obj['paymentDisputeSummaries'] = ApiClient.convertToType(data['paymentDisputeSummaries'], [PaymentDisputeSummary]);
            }
            if (data.hasOwnProperty('prev')) {
                obj['prev'] = ApiClient.convertToType(data['prev'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The URI of the getPaymentDisputeSummaries call request that produced the current page of the result set.
    * @member {String} href
    */
    'href' = undefined;
    /**
    * This value shows the maximum number of payment disputes that will appear on one page of the result set. The limit value can be passed in as a query parameter in the request, or if it is not used, it defaults to 200. If the value in the total field exceeds this limit value, there are multiple pages in the current result set. Min: 1; Max: 200; Default: 200
    * @member {Number} limit
    */
    'limit' = undefined;
    /**
    * The getPaymentDisputeSummaries call URI to use if you wish to view the next page of the result set. For example, the following URI returns records 11 thru 20 from the collection of payment disputes: path/payment_dispute_summary?limit=10&amp;offset=10 This field is only returned if there is a next page of results to view based on the current input criteria.
    * @member {String} next
    */
    'next' = undefined;
    /**
    * This integer value indicates the number of payment disputes skipped before listing the first payment dispute from the result set. The offset value can be passed in as a query parameter in the request, or if it is not used, it defaults to 0 and the first payment dispute of the result set is shown at the top of the response.
    * @member {Number} offset
    */
    'offset' = undefined;
    /**
    * Each payment dispute that matches the input criteria is returned under this array. If no payment disputes are found, an empty array is returned.
    * @member {Array.<module:model/PaymentDisputeSummary>} paymentDisputeSummaries
    */
    'paymentDisputeSummaries' = undefined;
    /**
    * The getPaymentDisputeSummaries call URI to use if you wish to view the previous page of the result set. For example, the following URI returns records 1 thru 10 from the collection of payment disputes: path/payment_dispute_summary?limit=10&amp;offset=0 This field is only returned if there is a previous page of results to view based on the current input criteria.
    * @member {String} prev
    */
    'prev' = undefined;
    /**
    * This integer value is the total number of payment disputes that matched the input criteria. If the total number of entries exceeds the value that was set for limit in the request payload, you will have to make multiple API calls to see all pages of the results set. This field is returned even if it is 0.
    * @member {Number} total
    */
    'total' = undefined;




}
