/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';

/**
* The EbayCollectAndRemitTax model module.
* @module model/EbayCollectAndRemitTax
* @version v1.17.0
*/
export default class EbayCollectAndRemitTax {
    /**
    * Constructs a new <code>EbayCollectAndRemitTax</code>.
    * This type contains information about the type and amount of tax that eBay will collect and remit to the state, province, country, or other taxing authority in the buyer&#x27;s location, as required by that taxing authority. &#x27;Collect and Remit&#x27; tax includes US state-mandated sales tax and &#x27;Goods and Services&#x27; tax that is applicable to Australian and New Zealand sellers.
    * @alias module:model/EbayCollectAndRemitTax
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>EbayCollectAndRemitTax</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EbayCollectAndRemitTax} obj Optional instance to populate.
    * @return {module:model/EbayCollectAndRemitTax} The populated <code>EbayCollectAndRemitTax</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EbayCollectAndRemitTax();
                        
            
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('taxType')) {
                obj['taxType'] = ApiClient.convertToType(data['taxType'], 'String');
            }
            if (data.hasOwnProperty('collectionMethod')) {
                obj['collectionMethod'] = ApiClient.convertToType(data['collectionMethod'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Amount} amount
    */
    'amount' = undefined;
    /**
    * The type of tax and fees that eBay will collect and remit to the taxing or fee authority. See the TaxTypeEnum type definition for more information about each tax or fee type. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:TaxTypeEnum'>eBay API documentation</a>
    * @member {String} taxType
    */
    'taxType' = undefined;
    /**
    * This field indicates the collection method used to collect the 'Collect and Remit' tax for the order. This field is always returned for orders subject to 'Collect and Remit' tax, and its value is always NET. Note: Although the collectionMethod field is returned for all orders subject to 'Collect and Remit' tax, the collectionMethod field and the CollectionMethodEnum type are not currently of any practical use, although this field may have use in the future. If and when the logic of this field is changed, this note will be updated and a note will also be added to the Release Notes. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:CollectionMethodEnum'>eBay API documentation</a>
    * @member {String} collectionMethod
    */
    'collectionMethod' = undefined;




}
