/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ErrorParameter model module.
* @module model/ErrorParameter
* @version v1.17.0
*/
export default class ErrorParameter {
    /**
    * Constructs a new <code>ErrorParameter</code>.
    * This type contains the name and value of an input parameter that contributed to a specific error or warning condition.
    * @alias module:model/ErrorParameter
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ErrorParameter</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorParameter} obj Optional instance to populate.
    * @return {module:model/ErrorParameter} The populated <code>ErrorParameter</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorParameter();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * This is the name of input field that caused an issue with the call request.
    * @member {String} name
    */
    'name' = undefined;
    /**
    * This is the actual value that was passed in for the element specified in the name field.
    * @member {String} value
    */
    'value' = undefined;




}
