/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The FileInfo model module.
* @module model/FileInfo
* @version v1.17.0
*/
export default class FileInfo {
    /**
    * Constructs a new <code>FileInfo</code>.
    * This type is used by the files array, which shows the name, ID, file type, and upload date for each provided evidential file.
    * @alias module:model/FileInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>FileInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FileInfo} obj Optional instance to populate.
    * @return {module:model/FileInfo} The populated <code>FileInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileInfo();
                        
            
            if (data.hasOwnProperty('fileId')) {
                obj['fileId'] = ApiClient.convertToType(data['fileId'], 'String');
            }
            if (data.hasOwnProperty('fileType')) {
                obj['fileType'] = ApiClient.convertToType(data['fileType'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('uploadedDate')) {
                obj['uploadedDate'] = ApiClient.convertToType(data['uploadedDate'], 'String');
            }
        }
        return obj;
    }

    /**
    * The unique identifier of the evidence file.
    * @member {String} fileId
    */
    'fileId' = undefined;
    /**
    * The type of file uploaded. Supported file extensions are .JPEG, .JPG, and .PNG., and maximum file size allowed is 1.5 MB.
    * @member {String} fileType
    */
    'fileType' = undefined;
    /**
    * The seller-provided name of the evidence file.
    * @member {String} name
    */
    'name' = undefined;
    /**
    * The timestamp in this field shows the date/time when the seller uploaded the evidential document to eBay. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} uploadedDate
    */
    'uploadedDate' = undefined;




}
