/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The FileEvidence model module.
* @module model/FileEvidence
* @version v1.17.0
*/
export default class FileEvidence {
    /**
    * Constructs a new <code>FileEvidence</code>.
    * This type is used to store the unique identifier of an evidence file. Evidence files are used by seller to contest a payment dispute.
    * @alias module:model/FileEvidence
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>FileEvidence</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FileEvidence} obj Optional instance to populate.
    * @return {module:model/FileEvidence} The populated <code>FileEvidence</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileEvidence();
                        
            
            if (data.hasOwnProperty('fileId')) {
                obj['fileId'] = ApiClient.convertToType(data['fileId'], 'String');
            }
        }
        return obj;
    }

    /**
    * If an uploadEvidenceFile call is successful, a unique identifier of this evidence file will be returned in the uploadEvidenceFile response payload. This unique fileId value is then used to either add this evidence file to a new evidence set using the addEvidence method, or to add this file to an existing evidence set using the updateEvidence method. Note that if an evidence set already exists for a payment dispute, the getPaymentDispute method will return both the evidenceId (unique identifier of evidence set) value, and the fileId (unique identifier of a file within that evidence set) value(s).
    * @member {String} fileId
    */
    'fileId' = undefined;




}
