/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import PickupStep from './PickupStep';
import ShippingStep from './ShippingStep';

/**
* The FulfillmentStartInstruction model module.
* @module model/FulfillmentStartInstruction
* @version v1.17.0
*/
export default class FulfillmentStartInstruction {
    /**
    * Constructs a new <code>FulfillmentStartInstruction</code>.
    * This type contains a set of specifications for processing a fulfillment of an order, including the type of fulfillment, shipping carrier and service, addressing details, and estimated delivery window. These instructions are derived from the buyer&#x27;s and seller&#x27;s eBay account preferences, the listing parameters, and the buyer&#x27;s checkout selections. The seller can use them as a starting point for packaging, addressing, and shipping the order.
    * @alias module:model/FulfillmentStartInstruction
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>FulfillmentStartInstruction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FulfillmentStartInstruction} obj Optional instance to populate.
    * @return {module:model/FulfillmentStartInstruction} The populated <code>FulfillmentStartInstruction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FulfillmentStartInstruction();
                        
            
            if (data.hasOwnProperty('ebaySupportedFulfillment')) {
                obj['ebaySupportedFulfillment'] = ApiClient.convertToType(data['ebaySupportedFulfillment'], 'Boolean');
            }
            if (data.hasOwnProperty('finalDestinationAddress')) {
                obj['finalDestinationAddress'] = Address.constructFromObject(data['finalDestinationAddress']);
            }
            if (data.hasOwnProperty('fulfillmentInstructionsType')) {
                obj['fulfillmentInstructionsType'] = ApiClient.convertToType(data['fulfillmentInstructionsType'], 'String');
            }
            if (data.hasOwnProperty('maxEstimatedDeliveryDate')) {
                obj['maxEstimatedDeliveryDate'] = ApiClient.convertToType(data['maxEstimatedDeliveryDate'], 'String');
            }
            if (data.hasOwnProperty('minEstimatedDeliveryDate')) {
                obj['minEstimatedDeliveryDate'] = ApiClient.convertToType(data['minEstimatedDeliveryDate'], 'String');
            }
            if (data.hasOwnProperty('pickupStep')) {
                obj['pickupStep'] = PickupStep.constructFromObject(data['pickupStep']);
            }
            if (data.hasOwnProperty('shippingStep')) {
                obj['shippingStep'] = ShippingStep.constructFromObject(data['shippingStep']);
            }
        }
        return obj;
    }

    /**
    * This field is only returned if its value is true and indicates that the fulfillment will be shipped via eBay's Global Shipping Program. For more information, see the Global Shipping Program help topic.
    * @member {Boolean} ebaySupportedFulfillment
    */
    'ebaySupportedFulfillment' = undefined;
    /**
    * @member {module:model/Address} finalDestinationAddress
    */
    'finalDestinationAddress' = undefined;
    /**
    * The enumeration value returned in this field indicates the method of fulfillment that will be used to deliver this set of line items (this package) to the buyer. This field will have a value of SHIP_TO if the ebaySupportedFulfillment field is returned with a value of true. See the FulfillmentInstructionsType definition for more information about different fulfillment types. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:FulfillmentInstructionsType'>eBay API documentation</a>
    * @member {String} fulfillmentInstructionsType
    */
    'fulfillmentInstructionsType' = undefined;
    /**
    * This is the estimated latest date that the fulfillment will be completed. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. This field is not returned ifthe value of the fulfillmentInstructionsType field is DIGITAL or PREPARE_FOR_PICKUP. Format: [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z Example: 2015-08-04T19:09:02.768Z
    * @member {String} maxEstimatedDeliveryDate
    */
    'maxEstimatedDeliveryDate' = undefined;
    /**
    * This is the estimated earliest date that the fulfillment will be completed. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. This field is not returned if the value of the fulfillmentInstructionsType field is DIGITAL or PREPARE_FOR_PICKUP. Format: [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z Example: 2015-08-04T19:09:02.768Z
    * @member {String} minEstimatedDeliveryDate
    */
    'minEstimatedDeliveryDate' = undefined;
    /**
    * @member {module:model/PickupStep} pickupStep
    */
    'pickupStep' = undefined;
    /**
    * @member {module:model/ShippingStep} shippingStep
    */
    'shippingStep' = undefined;




}
