/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GiftDetails model module.
* @module model/GiftDetails
* @version v1.17.0
*/
export default class GiftDetails {
    /**
    * Constructs a new <code>GiftDetails</code>.
    * This type contains information about a digital gift card line item that was purchased as a gift, and sent to the recipient by email.
    * @alias module:model/GiftDetails
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GiftDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GiftDetails} obj Optional instance to populate.
    * @return {module:model/GiftDetails} The populated <code>GiftDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GiftDetails();
                        
            
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('recipientEmail')) {
                obj['recipientEmail'] = ApiClient.convertToType(data['recipientEmail'], 'String');
            }
            if (data.hasOwnProperty('senderName')) {
                obj['senderName'] = ApiClient.convertToType(data['senderName'], 'String');
            }
        }
        return obj;
    }

    /**
    * This field contains the gift message from the buyer to the gift recipient. This field is only returned if the buyer of the gift included a message for the gift.
    * @member {String} message
    */
    'message' = undefined;
    /**
    * The email address of the gift recipient. The seller will send the digital gift card to this email address.
    * @member {String} recipientEmail
    */
    'recipientEmail' = undefined;
    /**
    * The name of the buyer, which will appear on the email that is sent to the gift recipient.
    * @member {String} senderName
    */
    'senderName' = undefined;




}
