/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LineItemReference model module.
* @module model/LineItemReference
* @version v1.17.0
*/
export default class LineItemReference {
    /**
    * Constructs a new <code>LineItemReference</code>.
    * This type identifies the line item and quantity of that line item that comprises one fulfillment, such as a shipping package.
    * @alias module:model/LineItemReference
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LineItemReference</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LineItemReference} obj Optional instance to populate.
    * @return {module:model/LineItemReference} The populated <code>LineItemReference</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LineItemReference();
                        
            
            if (data.hasOwnProperty('lineItemId')) {
                obj['lineItemId'] = ApiClient.convertToType(data['lineItemId'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
    * This is the unique identifier of the eBay order line item that is part of the shipping fulfillment. The line item ID is created as soon as there is a commitment to buy from the seller.
    * @member {String} lineItemId
    */
    'lineItemId' = undefined;
    /**
    * This field is reserved for internal or future use.
    * @member {Number} quantity
    */
    'quantity' = undefined;




}
