/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';

/**
* The LineItemRefund model module.
* @module model/LineItemRefund
* @version v1.17.0
*/
export default class LineItemRefund {
    /**
    * Constructs a new <code>LineItemRefund</code>.
    * This type contains refund information for a line item.
    * @alias module:model/LineItemRefund
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LineItemRefund</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LineItemRefund} obj Optional instance to populate.
    * @return {module:model/LineItemRefund} The populated <code>LineItemRefund</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LineItemRefund();
                        
            
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('refundDate')) {
                obj['refundDate'] = ApiClient.convertToType(data['refundDate'], 'String');
            }
            if (data.hasOwnProperty('refundId')) {
                obj['refundId'] = ApiClient.convertToType(data['refundId'], 'String');
            }
            if (data.hasOwnProperty('refundReferenceId')) {
                obj['refundReferenceId'] = ApiClient.convertToType(data['refundReferenceId'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Amount} amount
    */
    'amount' = undefined;
    /**
    * The date and time that the refund was issued for the line item. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. This field is not returned until the refund has been issued. Format: [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z Example: 2015-08-04T19:09:02.768Z
    * @member {String} refundDate
    */
    'refundDate' = undefined;
    /**
    * Unique identifier of a refund that was initiated for an order's line item through the issueRefund method. If the issueRefund method was used to issue a refund at the order level, this identifier is returned at the order level instead (paymentSummary.refunds.refundId field). A refundId value is returned in the response of the issueRefund method, and this same value will be returned in the getOrder and getOrders responses for pending and completed refunds. The issueRefund method can only be used for eBay managed payment orders.
    * @member {String} refundId
    */
    'refundId' = undefined;
    /**
    * This field is reserved for internal or future use.
    * @member {String} refundReferenceId
    */
    'refundReferenceId' = undefined;




}
