/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';
import AppliedPromotion from './AppliedPromotion';
import DeliveryCost from './DeliveryCost';
import EbayCollectAndRemitTax from './EbayCollectAndRemitTax';
import GiftDetails from './GiftDetails';
import LineItemFulfillmentInstructions from './LineItemFulfillmentInstructions';
import LineItemProperties from './LineItemProperties';
import LineItemRefund from './LineItemRefund';
import Tax from './Tax';

/**
* The LineItem model module.
* @module model/LineItem
* @version v1.17.0
*/
export default class LineItem {
    /**
    * Constructs a new <code>LineItem</code>.
    * This type contains the details of each line item in an order.
    * @alias module:model/LineItem
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LineItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LineItem} obj Optional instance to populate.
    * @return {module:model/LineItem} The populated <code>LineItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LineItem();
                        
            
            if (data.hasOwnProperty('appliedPromotions')) {
                obj['appliedPromotions'] = ApiClient.convertToType(data['appliedPromotions'], [AppliedPromotion]);
            }
            if (data.hasOwnProperty('deliveryCost')) {
                obj['deliveryCost'] = DeliveryCost.constructFromObject(data['deliveryCost']);
            }
            if (data.hasOwnProperty('discountedLineItemCost')) {
                obj['discountedLineItemCost'] = Amount.constructFromObject(data['discountedLineItemCost']);
            }
            if (data.hasOwnProperty('ebayCollectAndRemitTaxes')) {
                obj['ebayCollectAndRemitTaxes'] = ApiClient.convertToType(data['ebayCollectAndRemitTaxes'], [EbayCollectAndRemitTax]);
            }
            if (data.hasOwnProperty('giftDetails')) {
                obj['giftDetails'] = GiftDetails.constructFromObject(data['giftDetails']);
            }
            if (data.hasOwnProperty('legacyItemId')) {
                obj['legacyItemId'] = ApiClient.convertToType(data['legacyItemId'], 'String');
            }
            if (data.hasOwnProperty('legacyVariationId')) {
                obj['legacyVariationId'] = ApiClient.convertToType(data['legacyVariationId'], 'String');
            }
            if (data.hasOwnProperty('lineItemCost')) {
                obj['lineItemCost'] = Amount.constructFromObject(data['lineItemCost']);
            }
            if (data.hasOwnProperty('lineItemFulfillmentInstructions')) {
                obj['lineItemFulfillmentInstructions'] = LineItemFulfillmentInstructions.constructFromObject(data['lineItemFulfillmentInstructions']);
            }
            if (data.hasOwnProperty('lineItemFulfillmentStatus')) {
                obj['lineItemFulfillmentStatus'] = ApiClient.convertToType(data['lineItemFulfillmentStatus'], 'String');
            }
            if (data.hasOwnProperty('lineItemId')) {
                obj['lineItemId'] = ApiClient.convertToType(data['lineItemId'], 'String');
            }
            if (data.hasOwnProperty('listingMarketplaceId')) {
                obj['listingMarketplaceId'] = ApiClient.convertToType(data['listingMarketplaceId'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = LineItemProperties.constructFromObject(data['properties']);
            }
            if (data.hasOwnProperty('purchaseMarketplaceId')) {
                obj['purchaseMarketplaceId'] = ApiClient.convertToType(data['purchaseMarketplaceId'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('refunds')) {
                obj['refunds'] = ApiClient.convertToType(data['refunds'], [LineItemRefund]);
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('soldFormat')) {
                obj['soldFormat'] = ApiClient.convertToType(data['soldFormat'], 'String');
            }
            if (data.hasOwnProperty('taxes')) {
                obj['taxes'] = ApiClient.convertToType(data['taxes'], [Tax]);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = Amount.constructFromObject(data['total']);
            }
        }
        return obj;
    }

    /**
    * This array contains information about one or more sales promotions or discounts applied to the line item. It is always returned, but will be returned as an empty array if no special sales promotions or discounts apply to the order line item.
    * @member {Array.<module:model/AppliedPromotion>} appliedPromotions
    */
    'appliedPromotions' = undefined;
    /**
    * @member {module:model/DeliveryCost} deliveryCost
    */
    'deliveryCost' = undefined;
    /**
    * @member {module:model/Amount} discountedLineItemCost
    */
    'discountedLineItemCost' = undefined;
    /**
    * This container will be returned if the order line item is subject to a 'Collect and Remit' tax that eBay will collect and remit to the proper taxing authority on the buyer's behalf. 'Collect and Remit' tax includes US state-mandated sales tax and 'Goods and Services' tax (collected in Australia and New Zealand). The amount of this tax is shown in the amount field, and the type of tax is shown in the taxType field. eBay will display the tax type and amount during checkout in accordance with the buyer's address, and handle collection and remittance of the tax without requiring the seller to take any action.
    * @member {Array.<module:model/EbayCollectAndRemitTax>} ebayCollectAndRemitTaxes
    */
    'ebayCollectAndRemitTaxes' = undefined;
    /**
    * @member {module:model/GiftDetails} giftDetails
    */
    'giftDetails' = undefined;
    /**
    * The eBay-generated legacy listing item ID of the listing. Note that the unique identifier of a listing in REST-based APIs is called the listingId instead.
    * @member {String} legacyItemId
    */
    'legacyItemId' = undefined;
    /**
    * The unique identifier of a single variation within a multiple-variation listing. This field is only returned if the line item purchased was from a multiple-variation listing.
    * @member {String} legacyVariationId
    */
    'legacyVariationId' = undefined;
    /**
    * @member {module:model/Amount} lineItemCost
    */
    'lineItemCost' = undefined;
    /**
    * @member {module:model/LineItemFulfillmentInstructions} lineItemFulfillmentInstructions
    */
    'lineItemFulfillmentInstructions' = undefined;
    /**
    * This enumeration value indicates the current fulfillment status of the line item. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:LineItemFulfillmentStatusEnum'>eBay API documentation</a>
    * @member {String} lineItemFulfillmentStatus
    */
    'lineItemFulfillmentStatus' = undefined;
    /**
    * This is the unique identifier of an eBay order line item. This field is created as soon as there is a commitment to buy from the seller.
    * @member {String} lineItemId
    */
    'lineItemId' = undefined;
    /**
    * The unique identifier of the eBay marketplace where the line item was listed. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
    * @member {String} listingMarketplaceId
    */
    'listingMarketplaceId' = undefined;
    /**
    * @member {module:model/LineItemProperties} properties
    */
    'properties' = undefined;
    /**
    * The unique identifier of the eBay marketplace where the line item was listed. Often, the listingMarketplaceId and the purchaseMarketplaceId identifier are the same, but there are occasions when an item will surface on multiple eBay marketplaces. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
    * @member {String} purchaseMarketplaceId
    */
    'purchaseMarketplaceId' = undefined;
    /**
    * The number of units of the line item in the order. These are represented as a group by a single lineItemId.
    * @member {Number} quantity
    */
    'quantity' = undefined;
    /**
    * This array is always returned, but is returned as an empty array unless the seller has submitted a partial or full refund to the buyer for the order. If a refund has occurred, the refund amount and refund date will be shown for each refund.
    * @member {Array.<module:model/LineItemRefund>} refunds
    */
    'refunds' = undefined;
    /**
    * Seller-defined Stock-Keeping Unit (SKU). This inventory identifier must be unique within the seller's eBay inventory. SKUs are optional when listing in the legacy/Trading API system, but SKUs are required when listing items through the Inventory API model.
    * @member {String} sku
    */
    'sku' = undefined;
    /**
    * The eBay listing type of the line item. The most common listing types are AUCTION and FIXED_PRICE. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:SoldFormatEnum'>eBay API documentation</a>
    * @member {String} soldFormat
    */
    'soldFormat' = undefined;
    /**
    * Contains a list of taxes applied to the line item, if any. This array is always returned, but will be returned as empty if no taxes are applicable to the line item, or if the seller is opted in to eBay managed payments.
    * @member {Array.<module:model/Tax>} taxes
    */
    'taxes' = undefined;
    /**
    * The title of the listing.
    * @member {String} title
    */
    'title' = undefined;
    /**
    * @member {module:model/Amount} total
    */
    'total' = undefined;




}
