/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';

/**
* The OrderRefund model module.
* @module model/OrderRefund
* @version v1.17.0
*/
export default class OrderRefund {
    /**
    * Constructs a new <code>OrderRefund</code>.
    * This type contains information about a refund issued for an order. This does not include line item level refunds.
    * @alias module:model/OrderRefund
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OrderRefund</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OrderRefund} obj Optional instance to populate.
    * @return {module:model/OrderRefund} The populated <code>OrderRefund</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderRefund();
                        
            
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('refundDate')) {
                obj['refundDate'] = ApiClient.convertToType(data['refundDate'], 'String');
            }
            if (data.hasOwnProperty('refundId')) {
                obj['refundId'] = ApiClient.convertToType(data['refundId'], 'String');
            }
            if (data.hasOwnProperty('refundReferenceId')) {
                obj['refundReferenceId'] = ApiClient.convertToType(data['refundReferenceId'], 'String');
            }
            if (data.hasOwnProperty('refundStatus')) {
                obj['refundStatus'] = ApiClient.convertToType(data['refundStatus'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Amount} amount
    */
    'amount' = undefined;
    /**
    * The date and time that the refund was issued. This timestamp is in ISO 8601 format, which uses the 24-hour Universal Coordinated Time (UTC) clock. This field is not returned until the refund has been issued. Format: [YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z Example: 2015-08-04T19:09:02.768Z
    * @member {String} refundDate
    */
    'refundDate' = undefined;
    /**
    * Unique identifier of a refund that was initiated for an order through the issueRefund method. If the issueRefund method was used to issue one or more refunds at the line item level, these refund identifiers are returned at the line item level instead (lineItems.refunds.refundId field). A refundId value is returned in the response of the issueRefund method, and this same value will be returned in the getOrders and getOrders responses for pending and completed refunds. The issueRefund method can only be used for eBay managed payment orders. For other refunds, see the refundReferenceId field.
    * @member {String} refundId
    */
    'refundId' = undefined;
    /**
    * The eBay-generated unique identifier for the refund. This field is not returned until the refund has been issued.
    * @member {String} refundReferenceId
    */
    'refundReferenceId' = undefined;
    /**
    * This enumeration value indicates the current status of the refund to the buyer. This container is always returned for each refund. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:RefundStatusEnum'>eBay API documentation</a>
    * @member {String} refundStatus
    */
    'refundStatus' = undefined;




}
