/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SimpleAmount from './SimpleAmount';

/**
* The PaymentDisputeOutcomeDetail model module.
* @module model/PaymentDisputeOutcomeDetail
* @version v1.17.0
*/
export default class PaymentDisputeOutcomeDetail {
    /**
    * Constructs a new <code>PaymentDisputeOutcomeDetail</code>.
    * This type is used by the resolution container that is returned for payment disputes that have been resolved.
    * @alias module:model/PaymentDisputeOutcomeDetail
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PaymentDisputeOutcomeDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentDisputeOutcomeDetail} obj Optional instance to populate.
    * @return {module:model/PaymentDisputeOutcomeDetail} The populated <code>PaymentDisputeOutcomeDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDisputeOutcomeDetail();
                        
            
            if (data.hasOwnProperty('fees')) {
                obj['fees'] = SimpleAmount.constructFromObject(data['fees']);
            }
            if (data.hasOwnProperty('protectionStatus')) {
                obj['protectionStatus'] = ApiClient.convertToType(data['protectionStatus'], 'String');
            }
            if (data.hasOwnProperty('reasonForClosure')) {
                obj['reasonForClosure'] = ApiClient.convertToType(data['reasonForClosure'], 'String');
            }
            if (data.hasOwnProperty('recoupAmount')) {
                obj['recoupAmount'] = SimpleAmount.constructFromObject(data['recoupAmount']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SimpleAmount} fees
    */
    'fees' = undefined;
    /**
    * This enumeration value indicates if the seller is fully protected, partially protected, or not protected by eBay for the payment dispute. This field is always returned once the payment dispute is resolved. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:ProtectionStatusEnum'>eBay API documentation</a>
    * @member {String} protectionStatus
    */
    'protectionStatus' = undefined;
    /**
    * The enumeration value returned in this field indicates the outcome of the payment dispute for the seller. This field is always returned once the payment dispute is resolved. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:OutcomeEnum'>eBay API documentation</a>
    * @member {String} reasonForClosure
    */
    'reasonForClosure' = undefined;
    /**
    * @member {module:model/SimpleAmount} recoupAmount
    */
    'recoupAmount' = undefined;




}
