/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SimpleAmount from './SimpleAmount';

/**
* The PaymentDisputeSummary model module.
* @module model/PaymentDisputeSummary
* @version v1.17.0
*/
export default class PaymentDisputeSummary {
    /**
    * Constructs a new <code>PaymentDisputeSummary</code>.
    * This type is used by each payment dispute that is returned with the getPaymentDisputeSummaries method.
    * @alias module:model/PaymentDisputeSummary
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PaymentDisputeSummary</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentDisputeSummary} obj Optional instance to populate.
    * @return {module:model/PaymentDisputeSummary} The populated <code>PaymentDisputeSummary</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDisputeSummary();
                        
            
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = SimpleAmount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('buyerUsername')) {
                obj['buyerUsername'] = ApiClient.convertToType(data['buyerUsername'], 'String');
            }
            if (data.hasOwnProperty('closedDate')) {
                obj['closedDate'] = ApiClient.convertToType(data['closedDate'], 'String');
            }
            if (data.hasOwnProperty('openDate')) {
                obj['openDate'] = ApiClient.convertToType(data['openDate'], 'String');
            }
            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
            if (data.hasOwnProperty('paymentDisputeId')) {
                obj['paymentDisputeId'] = ApiClient.convertToType(data['paymentDisputeId'], 'String');
            }
            if (data.hasOwnProperty('paymentDisputeStatus')) {
                obj['paymentDisputeStatus'] = ApiClient.convertToType(data['paymentDisputeStatus'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('respondByDate')) {
                obj['respondByDate'] = ApiClient.convertToType(data['respondByDate'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SimpleAmount} amount
    */
    'amount' = undefined;
    /**
    * This is the buyer's eBay user ID. This field is returned for all payment disputes returned in the response.
    * @member {String} buyerUsername
    */
    'buyerUsername' = undefined;
    /**
    * The timestamp in this field shows the date/time when the payment dispute was closed, so this field is only returned for payment disputes in the CLOSED state. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} closedDate
    */
    'closedDate' = undefined;
    /**
    * The timestamp in this field shows the date/time when the payment dispute was opened. This field is returned for payment disputes in all states. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} openDate
    */
    'openDate' = undefined;
    /**
    * This is the unique identifier of the order involved in the payment dispute. Note: eBay rolled out a new Order ID format in June 2019. The legacy APIs still support the old and new order ID format to identify orders, but only the new order ID format is supported in REST-based APIs.
    * @member {String} orderId
    */
    'orderId' = undefined;
    /**
    * This is the unique identifier of the payment dispute. This identifier is automatically created by eBay once the payment dispute comes into the eBay Managed Payments system. This identifier is passed in at the end of the getPaymentDispute call URI to retrieve a specific payment dispute. The getPaymentDispute method returns more details about a payment dispute than the getPaymentDisputeSummaries method.
    * @member {String} paymentDisputeId
    */
    'paymentDisputeId' = undefined;
    /**
    * The enumeration value in this field gives the current status of the payment dispute. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:DisputeStateEnum'>eBay API documentation</a>
    * @member {String} paymentDisputeStatus
    */
    'paymentDisputeStatus' = undefined;
    /**
    * The enumeration value in this field gives the reason why the buyer initiated the payment dispute. See DisputeReasonEnum type for a description of the supported reasons that buyers can give for initiating a payment dispute. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:DisputeReasonEnum'>eBay API documentation</a>
    * @member {String} reason
    */
    'reason' = undefined;
    /**
    * The timestamp in this field shows the date/time when the seller must response to a payment dispute, so this field is only returned for payment disputes in the ACTION_NEEDED state. For payment disputes that require action by the seller, that same seller must call getPaymentDispute to see the next action(s) that they can take against the payment dispute. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} respondByDate
    */
    'respondByDate' = undefined;




}
