/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentDisputeActivity from './PaymentDisputeActivity';

/**
* The PaymentDisputeActivityHistory model module.
* @module model/PaymentDisputeActivityHistory
* @version v1.17.0
*/
export default class PaymentDisputeActivityHistory {
    /**
    * Constructs a new <code>PaymentDisputeActivityHistory</code>.
    * This type is used by the base response of the getActivities method, and includes a log of all activities of a payment dispute, from creation to resolution.
    * @alias module:model/PaymentDisputeActivityHistory
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PaymentDisputeActivityHistory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentDisputeActivityHistory} obj Optional instance to populate.
    * @return {module:model/PaymentDisputeActivityHistory} The populated <code>PaymentDisputeActivityHistory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDisputeActivityHistory();
                        
            
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], [PaymentDisputeActivity]);
            }
        }
        return obj;
    }

    /**
    * This array holds all activities of a payment dispute, from creation to resolution. For each activity, the activity type, the actor, and a timestamp is shown. The getActivities response is dynamic, and grows with each recorded activity.
    * @member {Array.<module:model/PaymentDisputeActivity>} activity
    */
    'activity' = undefined;




}
