/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DisputeEvidence from './DisputeEvidence';
import EvidenceRequest from './EvidenceRequest';
import InfoFromBuyer from './InfoFromBuyer';
import OrderLineItems from './OrderLineItems';
import PaymentDisputeOutcomeDetail from './PaymentDisputeOutcomeDetail';
import ReturnAddress from './ReturnAddress';
import SimpleAmount from './SimpleAmount';

/**
* The PaymentDispute model module.
* @module model/PaymentDispute
* @version v1.17.0
*/
export default class PaymentDispute {
    /**
    * Constructs a new <code>PaymentDispute</code>.
    * This type is used by the base response of the getPaymentDispute method. The getPaymentDispute method retrieves detailed information on a specific payment dispute.
    * @alias module:model/PaymentDispute
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PaymentDispute</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentDispute} obj Optional instance to populate.
    * @return {module:model/PaymentDispute} The populated <code>PaymentDispute</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDispute();
                        
            
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = SimpleAmount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('availableChoices')) {
                obj['availableChoices'] = ApiClient.convertToType(data['availableChoices'], ['String']);
            }
            if (data.hasOwnProperty('buyerProvided')) {
                obj['buyerProvided'] = InfoFromBuyer.constructFromObject(data['buyerProvided']);
            }
            if (data.hasOwnProperty('buyerUsername')) {
                obj['buyerUsername'] = ApiClient.convertToType(data['buyerUsername'], 'String');
            }
            if (data.hasOwnProperty('closedDate')) {
                obj['closedDate'] = ApiClient.convertToType(data['closedDate'], 'String');
            }
            if (data.hasOwnProperty('evidence')) {
                obj['evidence'] = ApiClient.convertToType(data['evidence'], [DisputeEvidence]);
            }
            if (data.hasOwnProperty('evidenceRequests')) {
                obj['evidenceRequests'] = ApiClient.convertToType(data['evidenceRequests'], [EvidenceRequest]);
            }
            if (data.hasOwnProperty('lineItems')) {
                obj['lineItems'] = ApiClient.convertToType(data['lineItems'], [OrderLineItems]);
            }
            if (data.hasOwnProperty('openDate')) {
                obj['openDate'] = ApiClient.convertToType(data['openDate'], 'String');
            }
            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
            if (data.hasOwnProperty('paymentDisputeId')) {
                obj['paymentDisputeId'] = ApiClient.convertToType(data['paymentDisputeId'], 'String');
            }
            if (data.hasOwnProperty('paymentDisputeStatus')) {
                obj['paymentDisputeStatus'] = ApiClient.convertToType(data['paymentDisputeStatus'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('resolution')) {
                obj['resolution'] = PaymentDisputeOutcomeDetail.constructFromObject(data['resolution']);
            }
            if (data.hasOwnProperty('respondByDate')) {
                obj['respondByDate'] = ApiClient.convertToType(data['respondByDate'], 'String');
            }
            if (data.hasOwnProperty('returnAddress')) {
                obj['returnAddress'] = ReturnAddress.constructFromObject(data['returnAddress']);
            }
            if (data.hasOwnProperty('revision')) {
                obj['revision'] = ApiClient.convertToType(data['revision'], 'Number');
            }
            if (data.hasOwnProperty('sellerResponse')) {
                obj['sellerResponse'] = ApiClient.convertToType(data['sellerResponse'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SimpleAmount} amount
    */
    'amount' = undefined;
    /**
    * The value(s) returned in this array indicate the choices that the seller has when responding to the payment dispute. Once the seller has responded to the payment dispute, this field will no longer be shown, and instead, the sellerResponse field will show the decision that the seller made.
    * @member {Array.<String>} availableChoices
    */
    'availableChoices' = undefined;
    /**
    * @member {module:model/InfoFromBuyer} buyerProvided
    */
    'buyerProvided' = undefined;
    /**
    * This is the eBay user ID of the buyer that initiated the payment dispute.
    * @member {String} buyerUsername
    */
    'buyerUsername' = undefined;
    /**
    * The timestamp in this field shows the date/time when the payment dispute was closed, so this field is only returned for payment disputes in the CLOSED state. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} closedDate
    */
    'closedDate' = undefined;
    /**
    * This container shows any evidence that has been provided by the seller to contest the payment dispute. Evidence may include shipment tracking information, proof of authentication documentation, image(s) to proof that an item is as described, or financial documentation/invoice. This container is only returned if the seller has provided at least one document used as evidence against the payment dispute.
    * @member {Array.<module:model/DisputeEvidence>} evidence
    */
    'evidence' = undefined;
    /**
    * This container is returned if one or more evidence documents are being requested from the seller.
    * @member {Array.<module:model/EvidenceRequest>} evidenceRequests
    */
    'evidenceRequests' = undefined;
    /**
    * This array is used to identify one or more order line items associated with the payment dispute. There will always be at least one itemId/lineItemId pair returned in this array.
    * @member {Array.<module:model/OrderLineItems>} lineItems
    */
    'lineItems' = undefined;
    /**
    * The timestamp in this field shows the date/time when the payment dispute was opened. This field is returned for payment disputes in all states. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} openDate
    */
    'openDate' = undefined;
    /**
    * This is the unique identifier of the order involved in the payment dispute. Note: eBay rolled out a new Order ID format in June 2019. The legacy APIs still support the old and new order ID format to identify orders, but only the new order ID format is returned in REST-based API responses.
    * @member {String} orderId
    */
    'orderId' = undefined;
    /**
    * This is the unique identifier of the payment dispute. This is the same identifier that is passed in to the call URI. This identifier is automatically created by eBay once the payment dispute comes into the eBay Managed Payments system.
    * @member {String} paymentDisputeId
    */
    'paymentDisputeId' = undefined;
    /**
    * The enumeration value in this field gives the current status of the payment dispute. The status of a payment dispute partially determines other fields that are returned in the response. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:DisputeStateEnum'>eBay API documentation</a>
    * @member {String} paymentDisputeStatus
    */
    'paymentDisputeStatus' = undefined;
    /**
    * The enumeration value in this field gives the reason why the buyer initiated the payment dispute. See DisputeReasonEnum type for a description of the supported reasons that buyers can give for initiating a payment dispute. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:DisputeReasonEnum'>eBay API documentation</a>
    * @member {String} reason
    */
    'reason' = undefined;
    /**
    * @member {module:model/PaymentDisputeOutcomeDetail} resolution
    */
    'resolution' = undefined;
    /**
    * The timestamp in this field shows the date/time when the seller must response to a payment dispute, so this field is only returned for payment disputes in the ACTION_NEEDED state. For payment disputes that currently require action by the seller, that same seller should look at the availableChoices array to see the available actions. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} respondByDate
    */
    'respondByDate' = undefined;
    /**
    * @member {module:model/ReturnAddress} returnAddress
    */
    'returnAddress' = undefined;
    /**
    * This integer value indicates the revision number of the payment dispute. Each time an action is taken against a payment dispute, this integer value increases by 1.
    * @member {Number} revision
    */
    'revision' = undefined;
    /**
    * The enumeration value returned in this field indicates how the seller has responded to the payment dispute. The seller has the option of accepting the payment dispute and agreeing to issue a refund, accepting the payment dispute and agreeing to issue a refund as long as the buyer returns the item, or contesting the payment dispute. This field is returned as soon as the seller makes an initial decision on the payment dispute. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:SellerResponseEnum'>eBay API documentation</a>
    * @member {String} sellerResponse
    */
    'sellerResponse' = undefined;




}
