/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PaymentDisputeActivity model module.
* @module model/PaymentDisputeActivity
* @version v1.17.0
*/
export default class PaymentDisputeActivity {
    /**
    * Constructs a new <code>PaymentDisputeActivity</code>.
    * This type is used by each recorded activity on a payment dispute, from creation to resolution.
    * @alias module:model/PaymentDisputeActivity
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PaymentDisputeActivity</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentDisputeActivity} obj Optional instance to populate.
    * @return {module:model/PaymentDisputeActivity} The populated <code>PaymentDisputeActivity</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDisputeActivity();
                        
            
            if (data.hasOwnProperty('activityDate')) {
                obj['activityDate'] = ApiClient.convertToType(data['activityDate'], 'String');
            }
            if (data.hasOwnProperty('activityType')) {
                obj['activityType'] = ApiClient.convertToType(data['activityType'], 'String');
            }
            if (data.hasOwnProperty('actor')) {
                obj['actor'] = ApiClient.convertToType(data['actor'], 'String');
            }
        }
        return obj;
    }

    /**
    * The timestamp in this field shows the date/time of the payment dispute activity. The timestamps returned here use the ISO-8601 24-hour date and time format, and the time zone used is Universal Coordinated Time (UTC), also known as Greenwich Mean Time (GMT), or Zulu. The ISO-8601 format looks like this: yyyy-MM-ddThh:mm.ss.sssZ. An example would be 2019-08-04T19:09:02.768Z.
    * @member {String} activityDate
    */
    'activityDate' = undefined;
    /**
    * This enumeration value indicates the type of activity that occured on the payment dispute. For example, a value of DISPUTE_OPENED is returned when a payment disute is first created, a value indicating the seller's decision on the dispute, such as SELLER_CONTEST, is returned when seller makes a decision to accept or contest dispute, and a value of DISPUTE_CLOSED is returned when a payment disute is resolved. See ActivityEnum for an explanation of each of the values that may be returned here. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:ActivityEnum'>eBay API documentation</a>
    * @member {String} activityType
    */
    'activityType' = undefined;
    /**
    * This enumeration value indicates the actor that performed the action. Possible values include the BUYER, SELLER, CS_AGENT (eBay customer service), or SYSTEM. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:ActorEnum'>eBay API documentation</a>
    * @member {String} actor
    */
    'actor' = undefined;




}
