/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PhoneNumber model module.
* @module model/PhoneNumber
* @version v1.17.0
*/
export default class PhoneNumber {
    /**
    * Constructs a new <code>PhoneNumber</code>.
    * This type contains a string field representing a telephone number.
    * @alias module:model/PhoneNumber
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PhoneNumber</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PhoneNumber} obj Optional instance to populate.
    * @return {module:model/PhoneNumber} The populated <code>PhoneNumber</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PhoneNumber();
                        
            
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
        }
        return obj;
    }

    /**
    * The primary telephone number for the shipping recipient.
    * @member {String} phoneNumber
    */
    'phoneNumber' = undefined;




}
