/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PostSaleAuthenticationProgram model module.
* @module model/PostSaleAuthenticationProgram
* @version v1.17.0
*/
export default class PostSaleAuthenticationProgram {
    /**
    * Constructs a new <code>PostSaleAuthenticationProgram</code>.
    * This type is used to provide the status and outcome of an order line item going through the Authenticity Guarantee verification process.
    * @alias module:model/PostSaleAuthenticationProgram
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PostSaleAuthenticationProgram</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PostSaleAuthenticationProgram} obj Optional instance to populate.
    * @return {module:model/PostSaleAuthenticationProgram} The populated <code>PostSaleAuthenticationProgram</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostSaleAuthenticationProgram();
                        
            
            if (data.hasOwnProperty('outcomeReason')) {
                obj['outcomeReason'] = ApiClient.convertToType(data['outcomeReason'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * This field indicates the result of the authenticity verification inspection on an order line item. This field is not returned when the status value of the order line item is PENDING or PASSED. The possible values returned here are NOT_AUTHENTIC, NOT_AS_DESCRIBED, CUSTOMIZED, and MISCATEGORIZED. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:AuthenticityVerificationReasonEnum'>eBay API documentation</a>
    * @member {String} outcomeReason
    */
    'outcomeReason' = undefined;
    /**
    * The value in this field indicates whether the order line item has passed or failed the authenticity verification inspection, or if the inspection and/or results are still pending. The possible values returned here are PENDING, PASSED, FAILED, or PASSED_WITH_EXCEPTION. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:AuthenticityVerificationStatusEnum'>eBay API documentation</a>
    * @member {String} status
    */
    'status' = undefined;




}
