/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostSaleAuthenticationProgram from './PostSaleAuthenticationProgram';

/**
* The Program model module.
* @module model/Program
* @version v1.17.0
*/
export default class Program {
    /**
    * Constructs a new <code>Program</code>.
    * This type is used by the program container, which is returned for order line items eligible for the Authenticity Guarantee service.
    * @alias module:model/Program
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Program</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Program} obj Optional instance to populate.
    * @return {module:model/Program} The populated <code>Program</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Program();
                        
            
            if (data.hasOwnProperty('authenticityVerification')) {
                obj['authenticityVerification'] = PostSaleAuthenticationProgram.constructFromObject(data['authenticityVerification']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/PostSaleAuthenticationProgram} authenticityVerification
    */
    'authenticityVerification' = undefined;




}
