/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Phone from './Phone';

/**
* The ReturnAddress model module.
* @module model/ReturnAddress
* @version v1.17.0
*/
export default class ReturnAddress {
    /**
    * Constructs a new <code>ReturnAddress</code>.
    * This type is used by the payment dispute methods, and is relevant if the buyer will be returning the item to the seller.
    * @alias module:model/ReturnAddress
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ReturnAddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ReturnAddress} obj Optional instance to populate.
    * @return {module:model/ReturnAddress} The populated <code>ReturnAddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReturnAddress();
                        
            
            if (data.hasOwnProperty('addressLine1')) {
                obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
            }
            if (data.hasOwnProperty('addressLine2')) {
                obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('county')) {
                obj['county'] = ApiClient.convertToType(data['county'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('primaryPhone')) {
                obj['primaryPhone'] = Phone.constructFromObject(data['primaryPhone']);
            }
            if (data.hasOwnProperty('stateOrProvince')) {
                obj['stateOrProvince'] = ApiClient.convertToType(data['stateOrProvince'], 'String');
            }
        }
        return obj;
    }

    /**
    * The first line of the street address.
    * @member {String} addressLine1
    */
    'addressLine1' = undefined;
    /**
    * The second line of the street address. This line is not always necessarily, but is often used for apartment number or suite number, or other relevant information that can not fit on the first line.
    * @member {String} addressLine2
    */
    'addressLine2' = undefined;
    /**
    * The city of the return address.
    * @member {String} city
    */
    'city' = undefined;
    /**
    * The country's two-digt, ISO 3166-1 country code. See the enumeration type for a country's value. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/ba:CountryCodeEnum'>eBay API documentation</a>
    * @member {String} country
    */
    'country' = undefined;
    /**
    * The county of the return address. Counties are not applicable to all countries.
    * @member {String} county
    */
    'county' = undefined;
    /**
    * The full name of return address owner.
    * @member {String} fullName
    */
    'fullName' = undefined;
    /**
    * The postal code of the return address.
    * @member {String} postalCode
    */
    'postalCode' = undefined;
    /**
    * @member {module:model/Phone} primaryPhone
    */
    'primaryPhone' = undefined;
    /**
    * The state or province of the return address.
    * @member {String} stateOrProvince
    */
    'stateOrProvince' = undefined;




}
