/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SellerActionsToRelease model module.
* @module model/SellerActionsToRelease
* @version v1.17.0
*/
export default class SellerActionsToRelease {
    /**
    * Constructs a new <code>SellerActionsToRelease</code>.
    * This type is used to state possible action(s) that a seller can take to release a payment hold placed against an order.
    * @alias module:model/SellerActionsToRelease
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SellerActionsToRelease</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SellerActionsToRelease} obj Optional instance to populate.
    * @return {module:model/SellerActionsToRelease} The populated <code>SellerActionsToRelease</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SellerActionsToRelease();
                        
            
            if (data.hasOwnProperty('sellerActionToRelease')) {
                obj['sellerActionToRelease'] = ApiClient.convertToType(data['sellerActionToRelease'], 'String');
            }
        }
        return obj;
    }

    /**
    * A possible action that the seller can take to expedite the release of a payment hold. A sellerActionToRelease field is returned for each possible action that a seller may take. Possible actions may include providing shipping/tracking information, issuing a refund, providing refund information, contacting customer support, etc.
    * @member {String} sellerActionToRelease
    */
    'sellerActionToRelease' = undefined;




}
