/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Error from './Error';
import ShippingFulfillment from './ShippingFulfillment';

/**
* The ShippingFulfillmentPagedCollection model module.
* @module model/ShippingFulfillmentPagedCollection
* @version v1.17.0
*/
export default class ShippingFulfillmentPagedCollection {
    /**
    * Constructs a new <code>ShippingFulfillmentPagedCollection</code>.
    * This type contains the specifications for the entire collection of shipping fulfillments that are associated with the order specified by a getShippingFulfillments call. The fulfillments container returns an array of all the fulfillments in the collection.
    * @alias module:model/ShippingFulfillmentPagedCollection
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ShippingFulfillmentPagedCollection</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ShippingFulfillmentPagedCollection} obj Optional instance to populate.
    * @return {module:model/ShippingFulfillmentPagedCollection} The populated <code>ShippingFulfillmentPagedCollection</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShippingFulfillmentPagedCollection();
                        
            
            if (data.hasOwnProperty('fulfillments')) {
                obj['fulfillments'] = ApiClient.convertToType(data['fulfillments'], [ShippingFulfillment]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('warnings')) {
                obj['warnings'] = ApiClient.convertToType(data['warnings'], [Error]);
            }
        }
        return obj;
    }

    /**
    * This array contains one or more fulfillments required for the order that was specified in method endpoint.
    * @member {Array.<module:model/ShippingFulfillment>} fulfillments
    */
    'fulfillments' = undefined;
    /**
    * The total number of fulfillments in the specified order. Note: If no fulfillments are found for the order, this field is returned with a value of 0.
    * @member {Number} total
    */
    'total' = undefined;
    /**
    * This array is only returned if one or more errors or warnings occur with the call request.
    * @member {Array.<module:model/Error>} warnings
    */
    'warnings' = undefined;




}
