/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SimpleAmount model module.
* @module model/SimpleAmount
* @version v1.17.0
*/
export default class SimpleAmount {
    /**
    * Constructs a new <code>SimpleAmount</code>.
    * This type defines the monetary value of the payment dispute, and the currency used.
    * @alias module:model/SimpleAmount
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SimpleAmount</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SimpleAmount} obj Optional instance to populate.
    * @return {module:model/SimpleAmount} The populated <code>SimpleAmount</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleAmount();
                        
            
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * A three-letter ISO 4217 code (such as USD for US site) that indicates the currency of the amount in the value field. Both the value and currency fields are always returned with the amount container. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/ba:CurrencyCodeEnum'>eBay API documentation</a>
    * @member {String} currency
    */
    'currency' = undefined;
    /**
    * The monetary amount of the payment dispute. Both the value and currency fields are always returned with the amount container.
    * @member {String} value
    */
    'value' = undefined;




}
