/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Amount from './Amount';

/**
* The Tax model module.
* @module model/Tax
* @version v1.17.0
*/
export default class Tax {
    /**
    * Constructs a new <code>Tax</code>.
    * This type contains information about any sales tax applied to a line item.
    * @alias module:model/Tax
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Tax</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Tax} obj Optional instance to populate.
    * @return {module:model/Tax} The populated <code>Tax</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tax();
                        
            
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('taxType')) {
                obj['taxType'] = ApiClient.convertToType(data['taxType'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Amount} amount
    */
    'amount' = undefined;
    /**
    * Tax type. This field is only available when fieldGroups is set to TAX_BREAKDOWN. If the order has fees, a breakdown of the fees is also provided. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:TaxTypeEnum'>eBay API documentation</a>
    * @member {String} taxType
    */
    'taxType' = undefined;




}
