/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TaxIdentifier model module.
* @module model/TaxIdentifier
* @version v1.17.0
*/
export default class TaxIdentifier {
    /**
    * Constructs a new <code>TaxIdentifier</code>.
    * This type is used by the taxIdentifier container that is returned in getOrder. The taxIdentifier container consists of taxpayer identification information for buyers from Italy, Spain, or Guatemala. It is currently only returned for orders occurring on the eBay Italy or eBay Spain marketplaces. Note: Currently, the taxIdentifier container is only returned in getOrder and not in getOrders. So, if a seller wanted to view a buyer&#x27;s tax information for a particular order returned in getOrders, that seller would need to use the orderId value for that particular order, and then run a getOrder call against that order ID.
    * @alias module:model/TaxIdentifier
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TaxIdentifier</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TaxIdentifier} obj Optional instance to populate.
    * @return {module:model/TaxIdentifier} The populated <code>TaxIdentifier</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaxIdentifier();
                        
            
            if (data.hasOwnProperty('taxpayerId')) {
                obj['taxpayerId'] = ApiClient.convertToType(data['taxpayerId'], 'String');
            }
            if (data.hasOwnProperty('taxIdentifierType')) {
                obj['taxIdentifierType'] = ApiClient.convertToType(data['taxIdentifierType'], 'String');
            }
            if (data.hasOwnProperty('issuingCountry')) {
                obj['issuingCountry'] = ApiClient.convertToType(data['issuingCountry'], 'String');
            }
        }
        return obj;
    }

    /**
    * This value is the unique tax ID associated with the buyer. The type of tax identification is shown in the taxIdentifierType field.
    * @member {String} taxpayerId
    */
    'taxpayerId' = undefined;
    /**
    * This enumeration value indicates the type of tax identification being used for the buyer. The different tax types are defined in the TaxIdentifierTypeEnum type. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:TaxIdentifierTypeEnum'>eBay API documentation</a>
    * @member {String} taxIdentifierType
    */
    'taxIdentifierType' = undefined;
    /**
    * This two-letter code indicates the country that issued the buyer's tax ID. The country that the two-letter code represents can be found in the CountryCodeEnum type, or in the ISO 3166 standard. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/ba:CountryCodeEnum'>eBay API documentation</a>
    * @member {String} issuingCountry
    */
    'issuingCountry' = undefined;




}
