/**
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TrackingInfo model module.
* @module model/TrackingInfo
* @version v1.17.0
*/
export default class TrackingInfo {
    /**
    * Constructs a new <code>TrackingInfo</code>.
    * This type is used by the shipmentTracking array returned under the evidence container if the seller has provided shipment tracking information as evidence to support PROOF_OF_DELIVERY for an INR-related payment dispute.
    * @alias module:model/TrackingInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TrackingInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TrackingInfo} obj Optional instance to populate.
    * @return {module:model/TrackingInfo} The populated <code>TrackingInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrackingInfo();
                        
            
            if (data.hasOwnProperty('shipmentTrackingNumber')) {
                obj['shipmentTrackingNumber'] = ApiClient.convertToType(data['shipmentTrackingNumber'], 'String');
            }
            if (data.hasOwnProperty('shippingCarrierCode')) {
                obj['shippingCarrierCode'] = ApiClient.convertToType(data['shippingCarrierCode'], 'String');
            }
        }
        return obj;
    }

    /**
    * This string value represents the shipment tracking number of the package.
    * @member {String} shipmentTrackingNumber
    */
    'shipmentTrackingNumber' = undefined;
    /**
    * This string value represents the shipping carrier used to ship the package.
    * @member {String} shippingCarrierCode
    */
    'shippingCarrierCode' = undefined;




}
