name: CI PROD

on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # deploy only prod node red servers
#      - name: Deploy accounting-v2 node-red instance
#        run: curl ${{ secrets.ACCOUNTING_V2_NR_HOOK }}

      #      - name: Deploy cto node-red instance
      #        run: curl ${{secrets.CTO_NR_HOOK}}
        
      - uses: rollun-com/actions/update-d2c-service@master
        with:
          service-name: node-red
          d2c-email: ${{ secrets.D2C_USER }}
          d2c-password: ${{ secrets.D2C_PASSWORD }}
          
      - uses: rollun-com/actions/update-d2c-service@master
        with:
          service-name: dev-nr
          d2c-email: ${{ secrets.D2C_USER }}
          d2c-password: ${{ secrets.D2C_PASSWORD }}
        
      - uses: rollun-com/actions/update-d2c-service@master
        with:
          service-name: NR-megaplan
          d2c-email: ${{ secrets.D2C_USER }}
          d2c-password: ${{ secrets.D2C_PASSWORD }}
          
      - uses: rollun-com/actions/update-d2c-service@master
        with:
          service-name: ceo-node-red
          d2c-email: ${{ secrets.D2C_USER }}
          d2c-password: ${{ secrets.D2C_PASSWORD }}
