# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # deploy only dev node red servers
#      - name: Deploy dev manager node-red instance
#        run: curl ${{secrets.DEV_MANAGER_NR_HOOK}}

        #    - name: Deploy ceo node-red instance
        #      run: curl ${{secrets.CEO_NR_HOOK}}

      - uses: rollun-com/actions/update-d2c-service@master
        with:
          service-name: nr-accounting
          d2c-email: ${{ secrets.D2C_USER }}
          d2c-password: ${{ secrets.D2C_PASSWORD }}
          
      - uses: rollun-com/actions/update-d2c-service@master
        with:
          service-name: cto-nred
          d2c-email: ${{ secrets.D2C_USER }}
          d2c-password: ${{ secrets.D2C_PASSWORD }}

#    - name: Deploy accounting instance
#      run: curl ${{secrets.ACCOUNTING_NR_HOOK}}
#
#    - name: Deploy main node-red instance
#      run: curl ${{secrets.MAIN_NR_HOOK}}
#
#    - name: Deploy megaplan prod node-red instance
#      run: curl ${{secrets.MEGAPLAN_NR_HOOK}}
